a = int(input("Enter the 1st number "))
b = int(input("Enter the 2nd number "))
c = int(input("Enter the 3rd number "))
d = int(input("Enter the 4th number "))
x = (a + b) / (c+d)
x = float("{:2f}".format(x))
print(x)
